name: learning github action

on: push

jobs:
  apple:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "Hello from GitHub Actions!"

      - name: Print Node version
        run: node --version

        - name: Print environment variables
  run: env

- name: Print current directory
  run: pwd

      - name: List files
        run: ls -la